RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
API_SYSEX_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no

AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
